name: Upload Website-G

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main

        - name: S3 Sync
          uses: aws s3 sync . s3://urlshortnerg --exclude '.git/*'
