name: Upload Website-G

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main


        - name: install-aws-cli-action    
          uses: unfor19/install-aws-cli-action@v1
        
        
        


        - name: S3 Sync
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
          run: aws s3 sync . s3://urlshortnerg --exclude '.git/*' --debug
